---

name: "Code Quality"

on:
  - "push"
  - "pull_request"


jobs:
  pre-commit:
    name: "Code quality"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          #- 3.6
          #- 3.7
          - 3.8
          #- 3.9
        os:
          - "ubuntu-18.04"
          #- "macos-latest"
          #- "windows-latest"
    runs-on: "${{ matrix.os }}"#

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: "x64"

      - name: "Install python dependencies"
        run: "python -m pip install -r requirements.txt -v"

      - name: "Check linters versions"
        run: |
          python -m black --version
          python -m prospector --version
          python -m pylint --version

      - name: "Run black"
        run: "python -m black --check ./"

      - name: "Run prospector"
        run: "python -m prospector --absolute-paths --no-external-config --profile-path .prospector.yaml -w profile-validator -W pep257"

      - name: "Run mypy"
        run: "python -m mypy --config ./mypy.ini mputils"
