---

name: "Code Quality"

on:
  - "push"
  - "pull_request"


jobs:
  pre-commit:
    name: "Code quality"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          #- 3.6
          #- 3.7
          - 3.8
          #- 3.9
        os:
          - "ubuntu-18.04"
          #- "macos-latest"
          #- "windows-latest"
    runs-on: "${{ matrix.os }}"#

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Setup python"
        uses: "actions/setup-python@v1"

      - name: "Cache poetry"
        uses: "actions/cache@v1"
        env:
          # Increase this value to reset cache if env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: "~/.cache/pypoetry"
          key: "${{ matrix.os }}-poetry-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('poetry.lock') }}"

      - name: "Install python dependencies"
        run: "pip install -r requirements.txt -vvv"

      - name: "Run pre-commit"
        uses: "pre-commit/action@v2.0.0"
